[1.8.x] Update docker files from latest main
These have gone a bit out of sync among all the backporting

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -10,7 +10,7 @@ on:
       - release/*
 
 env:
-  registry: ghcr.io/internetstandards
+  DOCKER_REGISTRY: ghcr.io/${{ github.repository_owner }}
   # determine whether this pull request has permissions to push to registry, or artifacts
   # should be used to transfer images between jobs. Forked and dependabot builds don't
   # have permission to push to registry.
@@ -50,7 +50,7 @@ jobs:
       internetnl_version: ${{ steps.get_version.outputs.internetnl_version }}
 
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         # include vendor/ submodules used to build dependencies like nassl and unbound
         with:
           submodules: recursive
@@ -59,10 +59,11 @@ jobs:
         run: |
           # https://github.com/pypa/setuptools_scm/issues/414
           git fetch --prune --unshallow
-          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
+          # don't fail on this command if there are no tags (eg, on forked repos)
+          git fetch --depth=1 origin +refs/tags/*:refs/tags/* || true
 
       - name: Set up Python
-        uses: actions/setup-python@v4
+        uses: actions/setup-python@v5
         with:
           python-version: "3.10"
 
@@ -75,14 +76,14 @@ jobs:
 
       # login to pull images from Github registry
       - name: Login to GitHub Container Registry
-        uses: docker/login-action@v2
+        uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
+        uses: docker/setup-buildx-action@v3
 
       - name: Build ${{ matrix.image }} (for non-forked PR's)
         # build for non-forked PR's that are allowed to use the registry
@@ -97,10 +98,10 @@ jobs:
           # tag image with current setuptools_scm generated version
           # and tag with PR source branch (eg: feature-x)
           tags: |
-            ${{ env.registry }}/${{ matrix.image }}:${{ steps.get_version.outputs.internetnl_version }}
+            ${{ env.DOCKER_REGISTRY }}/${{ matrix.image }}:${{ steps.get_version.outputs.internetnl_version }}
           # use latest build from main, or image previously build by this PR for caching
           cache-from: |
-            ${{ env.registry }}/${{ matrix.image }}:main
+            ${{ env.DOCKER_REGISTRY }}/${{ matrix.image }}:main
           # push images to registry
           push: true
           # makes build images better usable as cache by allowing individual layers to be pulled from cache
@@ -122,11 +123,11 @@ jobs:
           # tag image with current setuptools_scm generated version
           # and tag with current branch name (eg: main)
           tags: |
-            ${{ env.registry }}/${{ matrix.image }}:${{ steps.get_version.outputs.internetnl_version }}
-            ${{ env.registry }}/${{ matrix.image }}:main
+            ${{ env.DOCKER_REGISTRY }}/${{ matrix.image }}:${{ steps.get_version.outputs.internetnl_version }}
+            ${{ env.DOCKER_REGISTRY }}/${{ matrix.image }}:main
           # use latest build from main for caching
           cache-from: |
-            ${{ env.registry }}/${{ matrix.image }}:main
+            ${{ env.DOCKER_REGISTRY }}/${{ matrix.image }}:main
           # push images to registry
           push: true
           # makes build images better usable as cache by allowing individual layers to be pulled from cache
@@ -147,11 +148,11 @@ jobs:
           target: ${{ matrix.target }}
           # tag image with current setuptools_scm generated version and tag 'latest'
           tags: |
-            ${{ env.registry }}/${{ matrix.image }}:${{ steps.get_version.outputs.internetnl_version }}
-            ${{ env.registry }}/${{ matrix.image }}:latest
+            ${{ env.DOCKER_REGISTRY }}/${{ matrix.image }}:${{ steps.get_version.outputs.internetnl_version }}
+            ${{ env.DOCKER_REGISTRY }}/${{ matrix.image }}:latest
           # use latest build from main for caching
           cache-from: |
-            ${{ env.registry }}/${{ matrix.image }}:main
+            ${{ env.DOCKER_REGISTRY }}/${{ matrix.image }}:main
           # push images to registry
           push: true
           # makes build images better usable as cache by allowing individual layers to be pulled from cache
@@ -172,10 +173,10 @@ jobs:
           target: ${{ matrix.target }}
           # tag image with current setuptools_scm generated version
           tags: |
-            ${{ env.registry }}/${{ matrix.image }}:${{ steps.get_version.outputs.internetnl_version }}
+            ${{ env.DOCKER_REGISTRY }}/${{ matrix.image }}:${{ steps.get_version.outputs.internetnl_version }}
           # use latest build from main for caching
           cache-from: |
-            ${{ env.registry }}/${{ matrix.image }}:main
+            ${{ env.DOCKER_REGISTRY }}/${{ matrix.image }}:main
           # don't push to registry due to permissions, but store in Docker so can be exported for artifacts below
           load: true
           # makes build images better usable as cache by allowing individual layers to be pulled from cache
@@ -186,12 +187,12 @@ jobs:
       - name: Save image to disk (for forked PR's or dependabot)
         # trigger only for forked PR's that don't have permissions to push to the container registry
         if: ${{ env.use_registry == 'false' }}
-        run: docker save ${{ env.registry }}/${{ matrix.image }}:${{ steps.get_version.outputs.internetnl_version }} | gzip > "${{ matrix.image }}.tar.gz"
+        run: docker save ${{ env.DOCKER_REGISTRY }}/${{ matrix.image }}:${{ steps.get_version.outputs.internetnl_version }} | gzip > "${{ matrix.image }}.tar.gz"
 
       - name: Upload image as build artifact (for forked PR's or dependabot)
         # trigger only for forked PR's that don't have permissions to push to the container registry
         if: ${{ env.use_registry == 'false' }}
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: "${{ matrix.image }}"
           path: "${{ matrix.image }}.tar.gz"
@@ -211,13 +212,14 @@ jobs:
 
               export BRANCH="${{ github.sha }}" && \\
               export RELEASE="${{ needs.build-docker.outputs.internetnl_version }}" && \\
+              export DOCKER_REGISTRY="${{env.DOCKER_REGISTRY}}" && \\
               cd /opt/Internet.nl/ && \\
-              curl -sSfO --output-dir docker https://raw.githubusercontent.com/internetstandards/Internet.nl/\$BRANCH/docker/defaults.env && \\
-              curl -sSfO --output-dir docker https://raw.githubusercontent.com/internetstandards/Internet.nl/\$BRANCH/docker/docker-compose.yml && \\
+              curl -sSfO --output-dir docker https://raw.githubusercontent.com/${{github.repository}}/\$BRANCH/docker/defaults.env && \\
+              curl -sSfO --output-dir docker https://raw.githubusercontent.com/${{github.repository}}/\$BRANCH/docker/docker-compose.yml && \\
               curl -sSfO https://raw.githubusercontent.com/${{github.repository}}/\$BRANCH/docker/user_manage.sh && \\
               chmod 755 user_manage.sh && \\
-              env -i RELEASE="\$RELEASE" docker compose --env-file=docker/defaults.env --env-file=docker/host.env --env-file=docker/local.env pull && \\
-              env -i RELEASE="\$RELEASE" docker compose --env-file=docker/defaults.env --env-file=docker/host.env --env-file=docker/local.env up --remove-orphans --wait --no-build
+              env -i RELEASE="\$RELEASE" DOCKER_REGISTRY="\$DOCKER_REGISTRY" docker compose --env-file=docker/defaults.env --env-file=docker/host.env --env-file=docker/local.env pull && \\
+              env -i RELEASE="\$RELEASE" DOCKER_REGISTRY="\$DOCKER_REGISTRY" docker compose --env-file=docker/defaults.env --env-file=docker/host.env --env-file=docker/local.env up --remove-orphans --wait --no-build
 
           EOF
 
@@ -230,13 +232,14 @@ jobs:
 
               export RELEASE="${{ needs.build-docker.outputs.internetnl_version }}" && \\
               export TAG="v\$RELEASE" && \\
+              export DOCKER_REGISTRY="${{env.DOCKER_REGISTRY}}" && \\
               cd /opt/Internet.nl/ && \\
-              curl -sSfO --output-dir docker https://raw.githubusercontent.com/internetstandards/Internet.nl/\$TAG/docker/defaults.env && \\
-              curl -sSfO --output-dir docker https://raw.githubusercontent.com/internetstandards/Internet.nl/\$TAG/docker/docker-compose.yml && \\
+              curl -sSfO --output-dir docker https://raw.githubusercontent.com/${{github.repository}}/\$TAG/docker/defaults.env && \\
+              curl -sSfO --output-dir docker https://raw.githubusercontent.com/${{github.repository}}/\$TAG/docker/docker-compose.yml && \\
               curl -sSfO https://raw.githubusercontent.com/${{github.repository}}/\$BRANCH/docker/user_manage.sh && \\
               chmod 755 user_manage.sh && \\
-              env -i RELEASE="\$RELEASE" docker compose --env-file=docker/defaults.env --env-file=docker/host.env --env-file=docker/local.env pull && \\
-              env -i RELEASE="\$RELEASE" docker compose --env-file=docker/defaults.env --env-file=docker/host.env --env-file=docker/local.env up --remove-orphans --wait --no-build
+              env -i RELEASE="\$RELEASE" DOCKER_REGISTRY="\$DOCKER_REGISTRY" docker compose --env-file=docker/defaults.env --env-file=docker/host.env --env-file=docker/local.env pull && \\
+              env -i RELEASE="\$RELEASE" DOCKER_REGISTRY="\$DOCKER_REGISTRY" docker compose --env-file=docker/defaults.env --env-file=docker/host.env --env-file=docker/local.env up --remove-orphans --wait --no-build
           EOF
 
   integration-test:
@@ -255,11 +258,11 @@ jobs:
           sudo systemctl restart docker.service
           sudo ip6tables -I DOCKER-USER --dst ff00::/8 -j ACCEPT
 
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
 
       # login to pull images from Github registry
       - name: Login to GitHub Container Registry
-        uses: docker/login-action@v2
+        uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
@@ -268,7 +271,7 @@ jobs:
       - name: Download images from artifacts (for forked PR's or dependabot)
         # trigger only for forked PR's that don't have permissions to push to the container registry
         if: ${{ env.use_registry == 'false' }}
-        uses: actions/download-artifact@v3
+        uses: actions/download-artifact@v4
         with:
           path: images/
 
@@ -302,7 +305,7 @@ jobs:
         if: always()
         run: make logs-all-dump env=test > docker-compose.log
 
-      - uses: test-summary/action@v2.1
+      - uses: test-summary/action@v2.3
         with:
           paths: test-results.xml
         if: always()
@@ -314,7 +317,7 @@ jobs:
         run: make docker-compose args="logs --tail=100" env=test
 
       - name: Archive test results
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         if: always()
         with:
           name: Playwright integration test results (screenshots, video)
@@ -322,7 +325,7 @@ jobs:
           if-no-files-found: ignore
 
       - name: Archive test results
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         if: always()
         with:
           name: Integration test Docker Compose Logs
@@ -339,11 +342,11 @@ jobs:
       RELEASE: "${{ needs.build-docker.outputs.internetnl_version }}"
 
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
 
       # login to pull images from Github registry
       - name: Login to GitHub Container Registry
-        uses: docker/login-action@v2
+        uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
@@ -352,7 +355,7 @@ jobs:
       - name: Download images from artifacts (for forked PR's or dependabot)
         # trigger only for forked PR's that don't have permissions to push to the container registry
         if: ${{ env.use_registry == 'false' }}
-        uses: actions/download-artifact@v3
+        uses: actions/download-artifact@v4
         with:
           path: images/
 
@@ -376,11 +379,11 @@ jobs:
       RELEASE: "${{ needs.build-docker.outputs.internetnl_version }}"
 
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
 
       # login to pull images from Github registry
       - name: Login to GitHub Container Registry
-        uses: docker/login-action@v2
+        uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
@@ -389,7 +392,7 @@ jobs:
       - name: Download images from artifacts (for forked PR's or dependabot)
         # trigger only for forked PR's that don't have permissions to push to the container registry
         if: ${{ env.use_registry == 'false' }}
-        uses: actions/download-artifact@v3
+        uses: actions/download-artifact@v4
         with:
           path: images/
 
@@ -413,7 +416,7 @@ jobs:
       - name: Run test
         run: make test
 
-      - uses: test-summary/action@v2.1
+      - uses: test-summary/action@v2.3
         with:
           paths: test-results.xml
         if: always()
@@ -428,11 +431,11 @@ jobs:
       RELEASE: "${{ needs.build-docker.outputs.internetnl_version }}"
 
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
 
       # login to pull images from Github registry
       - name: Login to GitHub Container Registry
-        uses: docker/login-action@v2
+        uses: docker/login-action@v3
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
@@ -441,7 +444,7 @@ jobs:
       - name: Download images from artifacts (for forked PR's or dependabot)
         # trigger only for forked PR's that don't have permissions to push to the container registry
         if: ${{ env.use_registry == 'false' }}
-        uses: actions/download-artifact@v3
+        uses: actions/download-artifact@v4
         with:
           path: images/
 
@@ -473,7 +476,7 @@ jobs:
         if: always()
         run: make logs-all-dump env=develop > docker-compose.log
 
-      - uses: test-summary/action@v2.1
+      - uses: test-summary/action@v2.3
         with:
           paths: test-results.xml
         if: always()
@@ -485,7 +488,7 @@ jobs:
         run: make docker-compose args="logs --tail=100" env=develop
 
       - name: Archive test results
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         if: always()
         with:
           name: Playwright development environment test results (screenshots, video)
@@ -493,7 +496,7 @@ jobs:
           if-no-files-found: ignore
 
       - name: Archive test results
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         if: always()
         with:
           name: Development environment test Docker Compose Logs
